pipeline:
  frontend:
    image: node:6
    commands:
      - npm install
      - npm test

  backend:
    image: golang
    commands:
      - go get
      - go build
      - go test

  notify:
    image: plugins/slack
    channel: developers
    username: drone
